# Generated by Django 2.0.1 on 2018-02-15 20:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=200)),
                ('url', models.URLField(default='', unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('icon', models.URLField(default='http://www.yourimage.com')),
                ('image', models.URLField(default='http://www.yourimage.com')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.Category')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.User_Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Game_Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.User_Profile')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.Game')),
            ],
        ),
    ]
