# Generated by Django 2.0.1 on 2018-02-02 21:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 2, 21, 17, 45, 119799, tzinfo=utc)),
        ),
    ]
