# Generated by Django 2.0 on 2018-02-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.URLField(default='http://www.image.com', max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.URLField(default='http://www.image.com', max_length=500),
        ),
    ]
