# Generated by Django 2.0.1 on 2018-01-30 15:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 15, 9, 15, 873243, tzinfo=utc)),
        ),
    ]
