# Generated by Django 2.0.1 on 2018-01-30 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0003_auto_20180130_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 16, 31, 12, 88162, tzinfo=utc)),
        ),
    ]
