# Generated by Django 2.0 on 2018-02-15 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0003_auto_20180213_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_score',
            name='game',
        ),
        migrations.RemoveField(
            model_name='game_score',
            name='player',
        ),
        migrations.DeleteModel(
            name='Game_Score',
        ),
    ]
