# Generated by Django 2.0.1 on 2018-02-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0004_auto_20180213_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(blank=True, default='', unique=True),
        ),
    ]
