# Generated by Django 2.0.1 on 2018-02-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0005_auto_20180214_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(default='', unique=True),
        ),
    ]
