# Generated by Django 2.0.1 on 2018-02-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0006_auto_20180214_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.URLField(default='http://www.yourimage.com'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.URLField(default='http://www.yourimage.com'),
        ),
    ]
