# Generated by Django 2.0.1 on 2018-02-15 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0007_auto_20180215_1341'),
        ('gameinfo', '0004_auto_20180215_0927'),
    ]

    operations = [
    ]
