# Generated by Django 2.0.1 on 2018-02-01 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        ('gameinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('_games', models.ManyToManyField(blank=True, default=None, to='gameinfo.Game')),
                ('_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.User_Profile')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
