# Generated by Django 2.0 on 2018-02-25 12:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        ('gameinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('played_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.User_Profile')),
                ('played_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Saved_Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField()),
                ('saved_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.User_Profile')),
                ('played_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameinfo.Game')),
            ],
        ),
    ]
