# Generated by Django 2.0 on 2018-02-20 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saved_game',
            old_name='settings',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='saved_game',
            name='status',
        ),
    ]
