# Generated by Django 2.0.1 on 2018-02-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameinfo', '0005_auto_20180201_1553'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='_ownedGames',
            field=models.ManyToManyField(blank=True, default=None, to='gameinfo.Game'),
        ),
    ]
