# Generated by Django 2.0 on 2018-02-25 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gameinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='_ownedGames',
            field=models.ManyToManyField(blank=True, default=None, to='gameinfo.Game'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
